api:
  - .github/filter.yml
  - .github/workflows/api-*.yml
  - apps/api/**

client:
  - .github/filter.yml
  - .github/workflows/client-*.yml
  - apps/client/**

graphql:
  - .github/filter.yml
  - .github/workflows/graphql-*.yml
  - apps/api/**
  - apps/client/codegen*.*

docker:
  - .github/filter.yml
  - .github/workflows/docker-*.yml
  - docker/**/*
  - .dockerignore
  - pnpm-lock.yaml
