tasks:
  - init: pnpm install

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - mikestead.dotenv
    - usernamehw.errorlens
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - graphql.vscode-graphql
    - vincaslt.highlight-matching-tag
    - ecmel.vscode-html-css
    - wix.vscode-import-cost
    - orta.vscode-jest
    - pkief.material-icon-theme
    - mongodb.mongodb-vscode
    - christian-kohler.path-intellisense
    - esbenp.prettier-vscode
    - prisma.prisma
    - stylelint.vscode-stylelint
    - tabnine.tabnine-vscode
    - bradlc.vscode-tailwindcss
    - hbenl.vscode-test-explorer
    - gruntfuggly.todo-tree
