name: api lint

on: push

env:
  node-version: 18

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      api: ${{ steps.changes.outputs.api }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/filter.yml

  lint-api:
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.api == 'true' }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: install
        run: yarn install --immutable

      - name: eslint
        run: yarn api lint --max-warnings=0

      - name: prettier
        run: yarn api fmt

  api-lint-check:
    runs-on: ubuntu-latest
    needs: lint-api
    if: ${{ ! failure() }}
    steps:
      - name: check
        run: echo "lint is successfully executed."
