name: client test

on: push

env:
  node-version: 18

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      client: ${{ steps.changes.outputs.client }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/filter.yml

  test:
    runs-on: ubuntu-latest
    needs: filter
    if: ${{ needs.filter.outputs.client == 'true' }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: setup pnpm
        uses: pnpm/action-setup@v2.2.4
        id: pnpm-install
        with:
          run_install: false
          version: 7.26.3

      - name: get pnpm store
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: install
        run: pnpm install --frozen-lockfile

      - name: setup graphql
        run: pnpm client gql:gen

      - name: unit test
        run: pnpm client test

  client-test-check:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ ! failure() }}
    steps:
      - name: check
        run: echo "test is successfully executed."
