name: client chromatic

on:
  push:
    branches:
      - main
  pull_request:

env:
  node-version: 18

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      client: ${{ steps.changes.outputs.client }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/filter.yml

  publish:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.client == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: install
        run: yarn install --immutable

      - name: setup graphql
        run: yarn client gql:gen

      - name: publish
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/client

  client-chromatic-check:
    runs-on: ubuntu-latest
    needs: publish
    if: ${{ ! failure() }}
    steps:
      - name: check
        run: echo "publish storybook is successfully executed."
